//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQuizCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleQuizCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string ButtonHelloContent {
            get {
                return ResourceManager.GetString("ButtonHelloContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ButtonHistoryContent {
            get {
                return ResourceManager.GetString("ButtonHistoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz list.
        /// </summary>
        public static string ButtonQuizListContent {
            get {
                return ResourceManager.GetString("ButtonQuizListContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ButtonRefreshContent {
            get {
                return ResourceManager.GetString("ButtonRefreshContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ButtonSettingsContent {
            get {
                return ResourceManager.GetString("ButtonSettingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new quiz!.
        /// </summary>
        public static string ButtonStartQuizContent {
            get {
                return ResourceManager.GetString("ButtonStartQuizContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string HeaderDate {
            get {
                return ResourceManager.GetString("HeaderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent score.
        /// </summary>
        public static string HeaderPercentScore {
            get {
                return ResourceManager.GetString("HeaderPercentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point score.
        /// </summary>
        public static string HeaderPointScore {
            get {
                return ResourceManager.GetString("HeaderPointScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question amount.
        /// </summary>
        public static string HeaderQuestionAmount {
            get {
                return ResourceManager.GetString("HeaderQuestionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz name.
        /// </summary>
        public static string HeaderQuizName {
            get {
                return ResourceManager.GetString("HeaderQuizName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score type.
        /// </summary>
        public static string HeaderScoreType {
            get {
                return ResourceManager.GetString("HeaderScoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of auto-generated answers:.
        /// </summary>
        public static string LabelAutogeneratedContent {
            get {
                return ResourceManager.GetString("LabelAutogeneratedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of questions:.
        /// </summary>
        public static string LabelQuestionNumberContent {
            get {
                return ResourceManager.GetString("LabelQuestionNumberContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of quizzes:.
        /// </summary>
        public static string LabelQuizListContent {
            get {
                return ResourceManager.GetString("LabelQuizListContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select quiz:.
        /// </summary>
        public static string LabelQuizSelectContent {
            get {
                return ResourceManager.GetString("LabelQuizSelectContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz settings:.
        /// </summary>
        public static string LabelQuizSettingsContent {
            get {
                return ResourceManager.GetString("LabelQuizSettingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score settings:.
        /// </summary>
        public static string LabelScoreSettingsContnet {
            get {
                return ResourceManager.GetString("LabelScoreSettingsContnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SimpleQuizCreator.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MenuItemClose {
            get {
                return ResourceManager.GetString("MenuItemClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close quiz.
        /// </summary>
        public static string QuizDialogCloseQuiz {
            get {
                return ResourceManager.GetString("QuizDialogCloseQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string QuizDialogFinishText {
            get {
                return ResourceManager.GetString("QuizDialogFinishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string QuizDialogNexQuestionText {
            get {
                return ResourceManager.GetString("QuizDialogNexQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your score:.
        /// </summary>
        public static string QuizDialogPercentScoreText {
            get {
                return ResourceManager.GetString("QuizDialogPercentScoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question:.
        /// </summary>
        public static string QuizDialogQuestionText {
            get {
                return ResourceManager.GetString("QuizDialogQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz finished!.
        /// </summary>
        public static string QuizDialogQuizFinished {
            get {
                return ResourceManager.GetString("QuizDialogQuizFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test consist of {0} questions.
        /// </summary>
        public static string QuizDialogQuizInfoText {
            get {
                return ResourceManager.GetString("QuizDialogQuizInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You scored {0} out of {1} points.
        /// </summary>
        public static string QuizDialogScoreText {
            get {
                return ResourceManager.GetString("QuizDialogScoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start quiz.
        /// </summary>
        public static string QuizDialogStartQuizText {
            get {
                return ResourceManager.GetString("QuizDialogStartQuizText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string QuizDialogTimeText {
            get {
                return ResourceManager.GetString("QuizDialogTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap QuizIcon {
            get {
                object obj = ResourceManager.GetObject("QuizIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string QuizPreviewText {
            get {
                return ResourceManager.GetString("QuizPreviewText", resourceCulture);
            }
        }
    }
}
