using SimpleQuizCreator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SimpleQuizCreator.Tests.FakeData
{
    public class FakeQuizFactory
    {

        public static Quiz NewQuiz3questions3asnwers()
        {
            Quiz quiz = new Quiz
            {
                Errors = new List<string>(),
                Name = "NewQuiz3questions3asnwers",
                Questions = new List<Question>()
                {
                    new Question { QuestionText = "Question 1", Answers = new List<Answer> {
                        new Answer { AnswerText = "Answer 1 - good", IsCorrect = true },
                        new Answer { AnswerText = "Answer 2", IsCorrect = false },
                        new Answer { AnswerText = "Answer 3", IsCorrect = false },
                    }},
                    new Question { QuestionText = "Question 2", Answers = new List<Answer> {
                        new Answer { AnswerText = "Answer 1", IsCorrect = false },
                        new Answer { AnswerText = "Answer 2 - good", IsCorrect = true },
                        new Answer { AnswerText = "Answer 3", IsCorrect = false },
                    }},
                    new Question { QuestionText = "Question 3", Answers = new List<Answer> {
                        new Answer { AnswerText = "Answer 1", IsCorrect = false },
                        new Answer { AnswerText = "Answer 2", IsCorrect = false },
                        new Answer { AnswerText = "Answer 3 - good", IsCorrect = true },
                    }},
                }
            };
            return quiz;
        }

        public static Quiz NewQuiz5questionsRandomAsnwers()
        {
            Quiz quiz = new Quiz
            {
                Errors = new List<string>(),
                Name = "NewQuiz5questionsRandomAsnwers",
                Questions = new List<Question>()
                {
                    new Question { QuestionText = "Question 1", Answers = new List<Answer> {
                        new Answer { AnswerText = "Answer 1 - good", IsCorrect = true },
                        new Answer { AnswerText = "Answer 2", IsCorrect = false },
                    }},
                    new Question { QuestionText = "Question 2", Answers = new List<Answer> {
                        new Answer { AnswerText = "Answer 1", IsCorrect = false },
                        new Answer { AnswerText = "Answer 2 - good", IsCorrect = true },
                        new Answer { AnswerText = "Answer 3", IsCorrect = false },
                    }},
                    new Question { QuestionText = "Question 3", Answers = new List<Answer> {
                        new Answer { AnswerText = "Answer 1", IsCorrect = false },
                        new Answer { AnswerText = "Answer 2", IsCorrect = false },
                        new Answer { AnswerText = "Answer 3 - good", IsCorrect = true },
                        new Answer { AnswerText = "Answer 4 - good", IsCorrect = true },
                    }},
                    new Question { QuestionText = "Question 4", Answers = new List<Answer> {
                        new Answer { AnswerText = "Answer 1", IsCorrect = false },
                        new Answer { AnswerText = "Answer 2 - good", IsCorrect = true },
                        new Answer { AnswerText = "Answer 3", IsCorrect = false },
                        new Answer { AnswerText = "Answer 4", IsCorrect = false },
                        new Answer { AnswerText = "Answer 5", IsCorrect = false },
                    }},
                    new Question { QuestionText = "Question 5", Answers = new List<Answer> {
                        new Answer { AnswerText = "Answer 1", IsCorrect = false },
                        new Answer { AnswerText = "Answer 2 - good", IsCorrect = true },
                        new Answer { AnswerText = "Answer 3", IsCorrect = false },
                        new Answer { AnswerText = "Answer 4 - good", IsCorrect = true },
                        new Answer { AnswerText = "Answer 5 - good", IsCorrect = true },
                        new Answer { AnswerText = "Answer 6 - good", IsCorrect = true },
                    }},
                }
            };
            return quiz;
        }

        public static Quiz NewBigSimpleAutogeneratedQuiz(int questions, int answers)
        {
            Quiz quiz = new Quiz();
            quiz.Name = "NewBigSimpleAutogeneratedQuiz";

            for(int i =0; i< questions; i++)
            {
                Question question = new Question();
                question.QuestionText = $"Question {i}";

                for(int x=0; x< answers;x++)
                {
                    Answer answer = new Answer();
                    if((x + i) % answers == 0)
                    {
                        answer.IsCorrect = true;
                        answer.AnswerText = $"Answer {x} - good";
                    } else
                    {
                        answer.AnswerText = $"Answer {x}";
                    }
                    question.Answers.Add(answer);
                }
                quiz.Questions.Add(question);
            }

            return quiz;
        }
    }
}
